---
title: "Non-Standard Evaluation"
subtitle: "and Metaprogramming in R"
author: "<a href='https://github.com/janusvm'>Janus Valberg-Madsen</a>"
date: "2018-10-02 @ Aalborg R User Group"
output:
  xaringan::moon_reader:
    css: [default, default-fonts, custom.css]
    lib_dir: libs
    nature:
      highlightStyle: monokai-sublime
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  error = FALSE,
  dev = "svg",
  fig.align = "center",
  fig.path = "figs/"
)

# Utility functions
script <- function(file) source(file.path("scripts", file))
fig <- function(file) file.path("figs", file)
fa <- function(icon) paste0('<i class="fa fa-', icon, '"></i>')
error_print <- function(expr) {
  e <- tryCatch(expr, error = function(e) e$message)
  cat("Error in [truncated]:", e, sep = "\n")
}
```

```{r intro, child = "input/intro.Rmd"}
```

---
layout: false

```{r metaprogramming, child = "input/metaprogramming.Rmd"}
```

---
layout: false

```{r howto, child = "input/howto.Rmd"}
```

---
layout: false

```{r applications, child = "input/applications.Rmd"}
```

---
layout: false

```{r links, child = "input/links.Rmd"}
```

---
layout: false
class: inverse, middle, center

# `r {emo::ji("sparkles")}` Thank you for your time `r {emo::ji("sparkles")}`
